### ISSUE TITLE
A build without the Mod Features

### ISSUE THREAD

**Issue by Dynamixus** [ArifRios1st/PVZ-Hyper-Fusion-Mod#1]
Yo, Dyna here. Can we have another build that don't have the mod features in the game? It's good for testing purposes but I figured it would be better if we ship out an English version that doesn't have a hack in it, since some people might not want it and it's also really broken.

I'd still like to have the reload textures and reload strings features though, as that defintely helps with the translation efforts.

Still very thankful for the work you've done here!

**Comment by ArifRios1st** [comment]
i make several build on [v0.0.3](https://github.com/ArifRios1st/PVZ-Hyper-Fusion-Mod/releases/tag/v0.0.3)
